#############################################################################
# Makefile for building: javadlogger
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Wed Oct 23 10:21:38 2013
# Project:  javadlogger.pro
# Template: app
# Command: $(QMAKE) -o Makefile javadlogger.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
CXXFLAGS = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -I/usr/include/qt3
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = filestat.h \
		fsusage.h \
		genericserver.h \
		../javacquire/javacquire.h \
		javadfsusage.h \
		javadloggui.h \
		javshared.h \
		recport.h \
		sats.h \
		sigstrength.h \
		simpleserver.h \
		simplesocket.h \
		skyview.h \
		statview.h \
		utility.h
SOURCES = filestat.cpp \
		fsusage.cpp \
		genericserver.cpp \
		javadfsusage.cpp \
		javadloggui.cpp \
		javshared.cpp \
		main.cpp \
		recport.cpp \
		sats.cpp \
		sigstrength.cpp \
		simpleserver.cpp \
		simplesocket.cpp \
		skyview.cpp \
		statview.cpp \
		utility.cpp
OBJECTS = filestat.o \
		fsusage.o \
		genericserver.o \
		javadfsusage.o \
		javadloggui.o \
		javshared.o \
		main.o \
		recport.o \
		sats.o \
		sigstrength.o \
		simpleserver.o \
		simplesocket.o \
		skyview.o \
		statview.o \
		utility.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_filestat.cpp \
		moc_fsusage.cpp \
		moc_genericserver.cpp \
		moc_javadfsusage.cpp \
		moc_javadloggui.cpp \
		moc_recport.cpp \
		moc_sigstrength.cpp \
		moc_simpleserver.cpp \
		moc_simplesocket.cpp \
		moc_skyview.cpp \
		moc_statview.cpp
OBJMOC = moc_filestat.o \
		moc_fsusage.o \
		moc_genericserver.o \
		moc_javadfsusage.o \
		moc_javadloggui.o \
		moc_recport.o \
		moc_sigstrength.o \
		moc_simpleserver.o \
		moc_simplesocket.o \
		moc_skyview.o \
		moc_statview.o
DIST	   = javadlogger.pro
QMAKE_TARGET = javadlogger
DESTDIR  = 
TARGET   = javadlogger

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: javadlogger.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile javadlogger.pro
qmake: 
	@$(QMAKE) -o Makefile javadlogger.pro

dist: 
	@mkdir -p .tmp/javadlogger && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/javadlogger/ && ( cd `dirname .tmp/javadlogger` && $(TAR) javadlogger.tar javadlogger && $(GZIP) javadlogger.tar ) && $(MOVE) `dirname .tmp/javadlogger`/javadlogger.tar.gz . && $(DEL_FILE) -r .tmp/javadlogger

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

filestat.o: filestat.cpp filestat.h \
		javshared.h \
		javacquire.h

fsusage.o: fsusage.cpp fsusage.h

genericserver.o: genericserver.cpp genericserver.h \
		simpleserver.h \
		simplesocket.h

javadfsusage.o: javadfsusage.cpp javadfsusage.h \
		javshared.h \
		javacquire.h

javadloggui.o: javadloggui.cpp javadloggui.h \
		utility.h \
		sats.h \
		fsusage.h \
		javadfsusage.h \
		filestat.h \
		skyview.h \
		sigstrength.h \
		javshared.h \
		statview.h \
		recport.h \
		genericserver.h \
		javacquire.h \
		simpleserver.h \
		simplesocket.h

javshared.o: javshared.cpp javshared.h \
		javacquire.h

main.o: main.cpp javadloggui.h \
		fsusage.h \
		javadfsusage.h \
		filestat.h \
		skyview.h \
		sigstrength.h \
		javshared.h \
		statview.h \
		recport.h \
		genericserver.h \
		javacquire.h \
		sats.h \
		simpleserver.h \
		simplesocket.h

recport.o: recport.cpp recport.h \
		javshared.h \
		javacquire.h

sats.o: sats.cpp sats.h \
		utility.h \
		javshared.h \
		javacquire.h

sigstrength.o: sigstrength.cpp sigstrength.h \
		utility.h \
		javshared.h \
		sats.h \
		javacquire.h

simpleserver.o: simpleserver.cpp simpleserver.h \
		simplesocket.h

simplesocket.o: simplesocket.cpp simplesocket.h

skyview.o: skyview.cpp skyview.h \
		utility.h \
		javshared.h \
		sats.h \
		javacquire.h

statview.o: statview.cpp statview.h \
		javshared.h \
		javacquire.h

utility.o: utility.cpp utility.h

moc_filestat.o: moc_filestat.cpp  filestat.h javshared.h \
		javacquire.h

moc_fsusage.o: moc_fsusage.cpp  fsusage.h 

moc_genericserver.o: moc_genericserver.cpp  genericserver.h simpleserver.h \
		simplesocket.h

moc_javadfsusage.o: moc_javadfsusage.cpp  javadfsusage.h javshared.h \
		javacquire.h

moc_javadloggui.o: moc_javadloggui.cpp  javadloggui.h fsusage.h \
		javadfsusage.h \
		filestat.h \
		skyview.h \
		sigstrength.h \
		javshared.h \
		statview.h \
		recport.h \
		genericserver.h \
		javacquire.h \
		sats.h \
		simpleserver.h \
		simplesocket.h

moc_recport.o: moc_recport.cpp  recport.h javshared.h \
		javacquire.h

moc_sigstrength.o: moc_sigstrength.cpp  sigstrength.h javshared.h \
		sats.h \
		javacquire.h

moc_simpleserver.o: moc_simpleserver.cpp  simpleserver.h simplesocket.h

moc_simplesocket.o: moc_simplesocket.cpp  simplesocket.h 

moc_skyview.o: moc_skyview.cpp  skyview.h javshared.h \
		sats.h \
		javacquire.h

moc_statview.o: moc_statview.cpp  statview.h javshared.h \
		javacquire.h

moc_filestat.cpp: $(MOC) filestat.h
	$(MOC) filestat.h -o moc_filestat.cpp

moc_fsusage.cpp: $(MOC) fsusage.h
	$(MOC) fsusage.h -o moc_fsusage.cpp

moc_genericserver.cpp: $(MOC) genericserver.h
	$(MOC) genericserver.h -o moc_genericserver.cpp

moc_javadfsusage.cpp: $(MOC) javadfsusage.h
	$(MOC) javadfsusage.h -o moc_javadfsusage.cpp

moc_javadloggui.cpp: $(MOC) javadloggui.h
	$(MOC) javadloggui.h -o moc_javadloggui.cpp

moc_recport.cpp: $(MOC) recport.h
	$(MOC) recport.h -o moc_recport.cpp

moc_sigstrength.cpp: $(MOC) sigstrength.h
	$(MOC) sigstrength.h -o moc_sigstrength.cpp

moc_simpleserver.cpp: $(MOC) simpleserver.h
	$(MOC) simpleserver.h -o moc_simpleserver.cpp

moc_simplesocket.cpp: $(MOC) simplesocket.h
	$(MOC) simplesocket.h -o moc_simplesocket.cpp

moc_skyview.cpp: $(MOC) skyview.h
	$(MOC) skyview.h -o moc_skyview.cpp

moc_statview.cpp: $(MOC) statview.h
	$(MOC) statview.h -o moc_statview.cpp

####### Install

install:  

uninstall:  

